CREATE DATABASE BRANDSS
CREATE DATABASE PRODUCTSS
USE BRANDSS
CREATE TABLE ITEMS_TABLE(
ITEM_ID INT PRIMARY KEY,
ITEM_DESCRIPTION VARCHAR(50),
VENDOR_NOS INT,
VENDOR_NAME VARCHAR(30),
BOTTLE_SIZE INT,
BOTTLE_PRICE FLOAT);

USE PRODUCTSS
CREATE TABLE PRODUCTS(
PRODUCT_ID INT PRIMARY KEY,
COUNTRY VARCHAR(20),
PRODUCT VARCHAR(30),
UNITS_SOLD FLOAT,
MANUFACTURING_PRICE DECIMAL,
SALE_PRICE INT,
GROSS_SALES INT,
SALES INT,
COGS INT,
PROFIT DECIMAL,
MANUFACTURING_DATE DATE,
MONTH_NUMBER INT,
MONTH_NAME VARCHAR(20),
MANUFACTURING_YEAR INT);

ALTER TABLE ITEMS_TABLE
ALTER COLUMN VENDOR_NAME VARCHAR(100)

SELECT* FROM ITEMS_TABLE

INSERT INTO ITEMS_TABLE(ITEM_ID,ITEM_DESCRIPTION ,VENDOR_NOS,VENDOR_NAME,BOTTLE_SIZE,BOTTLE_PRICE)
VALUES
(1,'Travis Hassle Apple Pie',305,'Mhw Ltd',750,9.77),
(2,'Daristi Xtabentun',391,'Anchor Distilling(preiss Imports)',750,14.12),
(3,'Hiram Walker Peach Brandy',370,'Pernod Ricard Usa/austin Nichols',1000,6.5),
(4,'OakCross Whisky',305,'Mhw Ltd',750,25.33),
(5,'Uv red(cherry)Vodka',380,'Philllips Beverage Company',200,1.97),
(6,'Heaven Hill Old Style White Label',259,'Heaven Hill Distilleries Inc.',750,6.37),
(7,'Hyde Herbal Liqueur',194,'Fire Tail Brands Lic',750,5.06),
(8,'Dupont Calvados Fine Reserve',403,'robert Kacher Selections',750,23.61);

SELECT * FROM PRODUCTS

INSERT INTO PRODUCTS(PRODUCT_ID,COUNTRY,PRODUCT,UNITS_SOLD,MANUFACTURING_PRICE,SALE_PRICE,GROSS_SALES,SALES,COGS,PROFIT,MANUFACTURING_DATE,MONTH_NUMBER,MONTH_NAME,MANUFACTURING_YEAR)
VALUES
(1,'Canada','Carretera',1618.5,3,20,32370,32370,16185,16185,'2014-01-01',1,'January',2014),
(2,'Germany','Carretera',1321,3,20,26420,26420,13210,13210,'2014-01-01',1,'January',2015),
(3,'France','Carretera',2178,3,15,32670,32670,21780,10890,'2014-01-06',6,'June',2016),
(4,'Germany','Carretera',888,3,15,13320,13320,8880,4440,'2014-01-06',6,'June',2017),
(5,'Mexico','Carretera',2470,3,15,37050,37050,24700,12350,'2014-01-06',6,'June',2018),
(6,'Germany','Carretera',1513,3,350,529550,529550,393380,136170,'2014-01-12',12,'December',2019),
(7,'Germany','Montana',921,5,15,13815,13815,9210,4605,'2014-01-03',3,'March',2020),
(8,'Canada','Montana',2518,5,12,30216,30216,7554,22662,'2014-01-06',6,'June',2021);

USE PRODUCTSS
SELECT * FROM PRODUCTS
USE BRANDSS
SELECT * FROM ITEMS_TABLE
--4
DELETE FROM PRODUCTS
WHERE UNITS_SOLD = 1618.5
DELETE FROM PRODUCTS
WHERE UNITS_SOLD IN (888,2470)

--5
USE BRANDSS
SELECT * FROM ITEMS_TABLE

--6
SELECT ITEM_DESCRIPTION, BOTTLE_PRICE FROM ITEMS_TABLE

--7
SELECT ITEM_DESCRIPTION, BOTTLE_PRICE FROM ITEMS_TABLE
WHERE BOTTLE_PRICE > 20

--8
USE PRODUCTSS
SELECT DISTINCT(COUNTRY) FROM PRODUCTS

--9
SELECT COUNT(COUNTRY)AS TOTAL_CON FROM PRODUCTS

--10
SELECT * FROM PRODUCTS
SELECT COUNTRY, SALE_PRICE FROM PRODUCTS
WHERE SALE_PRICE BETWEEN 10 AND 20

--INTERMEDIATE QUESTIONS

--1
SELECT SUM(SALE_PRICE)AS TOTAL_PRICE , SUM(GROSS_SALES) AS TOTAL_GROSS FROM PRODUCTS

--2
SELECT MANUFACTURING_YEAR FROM PRODUCTS WHERE SALES = (SELECT MAX(SALES) FROM PRODUCTS)

--3
SELECT PRODUCT FROM PRODUCTS
WHERE SALES =32670

--4
SELECT COUNTRY, PROFIT FROM PRODUCTS
WHERE PROFIT BETWEEN 4605 AND 22662

--5
SELECT PRODUCT_ID FROM PRODUCTS
WHERE SALES = 24700

--6
SELECT COUNTRY, SUM(UNITS_SOLD) AS TOTAL_SOLD FROM PRODUCTS
GROUP BY COUNTRY

--7
SELECT COUNTRY, AVG(UNITS_SOLD) AS AVGL_SOLD FROM PRODUCTS
GROUP BY COUNTRY

--9
SELECT * FROM PRODUCTS
SELECT MAX(PROFIT) AS MAXI_PROFIT FROM PRODUCTS

--11

USE BRANDSS
SELECT *FROM ITEMS_TABLE
SELECT ITEM_DESCRIPTION, BOTTLE_SIZE FROM ITEMS_TABLE
WHERE BOTTLE_SIZE = 750

--12
SELECT VENDOR_NAME, VENDOR_NOS FROM ITEMS_TABLE
WHERE VENDOR_NOS  IN (305, 380, 391)

--13
SELECT SUM(BOTTLE_PRICE) AS TOTAL_PRICE FROM ITEMS_TABLE

--15
SELECT ITEM_ID, BOTTLE_PRICE FROM   ITEMS_TABLE
WHERE BOTTLE_PRICE = 5.06

--ADVANCE QUESTIONS

--1
SELECT * FROM ITEMS_TABLE
SELECT * FROM PRODUCTS
SELECT I.iTEM_ID,I.ITEM_DESCRIPTION,I.VENDOR_NAME,I.BOTTLE_PRICE,P.PRODUCT_ID,P.COUNTRY,P.PRODUCT,P.UNITS_SOLD,P.SALES,P.PROFIT
  FROM BRANDS.dbo.ITEMS_TABLE  I
  JOIN PRODUCTS.dbo.PRODUCTS_TABLE P ON
  I.ITEM_ID = P.PRODUCT_ID;

  SELECT 
    I.ITEM_ID,
    I.ITEM_DESCRIPTION,
    I.VENDOR_NAME,
    I.BOTTLE_PRICE,
    P.PRODUCT_ID,
    P.COUNTRY,
    P.PRODUCT,
    P.UNITS_SOLD,
    P.SALES,
    P.PROFIT
FROM BRANDS.dbo.ITEMS_TABLE AS I
INNER JOIN PRODUCTS.dbo.PRODUCTS_TABLE AS P
ON I.ITEM_ID = P.PRODUCT_ID;

SELECT I.iTEM_ID,I.ITEM_DESCRIPTION,I.VENDOR_NAME,I.BOTTLE_PRICE,P.PRODUCT_ID,P.COUNTRY,P.PRODUCT,P.UNITS_SOLD,P.SALES,P.PROFIT
  FROM BRANDS.dbo.ITEMS_TABLE  I
  left JOIN PRODUCTS.dbo.PRODUCTS_TABLE P ON
  I.ITEM_ID = P.PRODUCT_ID;

SELECT I.iTEM_ID,I.ITEM_DESCRIPTION,I.VENDOR_NAME,I.BOTTLE_PRICE,P.PRODUCT_ID,P.COUNTRY,P.PRODUCT,P.UNITS_SOLD,P.SALES,P.PROFIT
  FROM BRANDS.dbo.ITEMS_TABLE  I
  FULL OUTER JOIN PRODUCTS.dbo.PRODUCTS_TABLE P ON
  I.ITEM_ID = P.PRODUCT_ID;

  --2
  SELECT I.ITEM_DESCRIPTION, P.PRODUCT_ID, P.GROSS_SALES
  FROM PRODUCTS P
  JOIN BRANDS.DBO.ITEMS_TABLE I
  ON P.PRODUCT_ID = I.ITEM_ID
  WHERE GROSS_SALES = 13320.00

  --4
SELECT TOP 3 ITEM_DESCRIPTION, BOTTLE_PRICE FROM ITEMS_TABLE
ORDER BY ITEM_DESCRIPTION DESC

--5
USE PRODUCTSS
SELECT * FROM PRODUCTS
SELECT SUM(GROSS_SALES) AS TOTAL_GROSS FROM PRODUCTSS, SUM(PROFIT) AS TOTAL_PRO, PROFIT,COUNTRY
FROM PRODUCTS
GROUP BY PRODUCT, COUNTRY
ORDER BY PRODUCT, COUNTRY DESC

--6
USE BRANDSS
SELECT VENDOR_NAME, ITEM_DESCRIPTION, BOTTLE_SIZE, BOTTLE_PRICE FROM ITEMS_TABLE
WHERE BOTTLE_SIZE = 750 AND BOTTLE_PRICE <10

--7
USE PRODUCTSS
SELECT * FROM PRODUCTS
SELECT PRODUCT, PROFIT FROM PRODUCTS
WHERE MANUFACTURING_YEAR = 2019
ORDER BY PROFIT DESC

--8
SELECT PRODUCT_ID, COUNTRY FROM PRODUCTS
WHERE PROFIT >= 2*COGS

--9
SELECT COUNTRY, SUM(GROSS_SALES) AS TOTAL_GROSS FROM PRODUCTS
WHERE MANUFACTURING_YEAR = 2018
GROUP BY COUNTRY
ORDER BY TOTAL_GROSS DESC

--SUPER-ADVANCE QUESTIONS
--1
USE BRANDSS
SELECT * FROM ITEMS_TABLE
SELECT ITEM_DESCRIPTION, BOTTLE_PRICE FROM ITEMS_TABLE
WHERE VENDOR_NAME =(
SELECT VENDOR_NAME
FROM ITEMS_TABLE
WHERE ITEM_ID = 1
);

--5
SELECT ITEM_DESCRIPTION FROM ITEMS_TABLE
WHERE ITEM_DESCRIPTION LIKE '%WHISKY'

--6
USE PRODUCTS
SELECT COUNTRY, PRODUCT FROM PRODUCTS_TABLE
WHERE PROFIT > (SELECT AVG(PROFIT)  AS AVERAGE_PROFIT FROM PRODUCTS_TABLE)

--10
SELECT MANUFACTURING_DATE,
DATEDIFF(DAY, MANUFACTURING_DATE,GETDATE()) AS DAYS_DIFFERENCE
FROM PRODUCTS_TABLE

