create database KMIT_UNIVERSITY
USE KMIT_UNIVERSITY
CREATE TABLE COLLEGE_TABLE(
COLLEGE_ID INT PRIMARY KEY,
COLLEGE_NAME VARCHAR(50),
COLLEGE_AREA VARCHAR(50)
)
CREATE TABLE DEPARTMENT_TABLE(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50),
DEPT_FACILITY VARCHAR(50)
)
CREATE TABLE PROFESSOR_TABLE(
PROFESSOR_ID INT PRIMARY KEY,
PROFESSOR_NAME VARCHAR(50),
PROFESSOR_SUBJECT VARCHAR(50)
)
CREATE TABLE STUDENT_TABLE(
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(50),
STUDENT_STREAM VARCHAR(50)
)
ALTER TABLE DEPARTMENT_TABLE
ADD COLLEGE_ID INT 
FOREIGN KEY REFERENCES COLLEGE_TABLE(COLLEGE_ID)
ALTER TABLE STUDENT_TABLE
ADD PROFESSOR_ID INT
FOREIGN KEY REFERENCES PROFESSOR_TABLE(PROFESSOR_ID)
SELECT * FROM COLLEGE_TABLE
SELECT * FROM DEPARTMENT_TABLE
SELECT * FROM PROFESSOR_TABLE
SELECT * FROM STUDENT_TABLE
INSERT INTO COLLEGE_TABLE(COLLEGE_ID, COLLEGE_NAME, COLLEGE_AREA)
VALUES
(1,'KMICS','DILSUKHNAGAR'),
(2,'KMICL','NARANGUDA'),
(3,'KMIJC','UPPUDA'),
(4,'SRI GAYATRI','PNTNAGAR'),
(5,'LOTUS LAP','SARRORNAGAR'),
(6,'PULLA REEDY','MALAKPET'),
(7,'NARAYANA','LBNAGAR'),
(8,'SRI SAI','VENKATESWARACOLONY'),
(9,'LILLY','NAGOLE'),
(10,'BHAVANS','CHAITANYAPURI')
SELECT * FROM COLLEGE_TABLE

INSERT INTO DEPARTMENT_TABLE(DEPT_ID,DEPT_NAME,DEPT_FACILITY)
VALUES
(101,'BCOM[GENERAL]','PRIYA'),
(102,'BCOM[COMPUTER SCIENCE]','RIYA'),
(103,'BCOM[HONOURS]','MEGHA'),
(104,'BCOM[COMPUTER APPLICATIONS]','SRUTHI'),
(105,'BSC[COMPUTER SCIENCE]','SHERYA'),
(106,'BSC[FOREIGN SCIENCE]','SRIKANTH'),
(107,'BSC[STATISTICS]','SRIPATH'),
(108,'BSC[BOITECH]','LADDU'),
(109,'BBA[ACCOUNTS]','NAIDU'),
(110,'BBA[FINANCE]','MITHUL')
SELECT * FROM DEPARTMENT_TABLE

INSERT INTO PROFESSOR_TABLE(PROFESSOR_ID,PROFESSOR_NAME,PROFESSOR_SUBJECT)
VALUES
(111,'GANA','STATISTICS'),
(112,'RANA','COMPUTERS'),
(113,'SANA','SANSKRITH'),
(114,'TANA','MATHAMETICS'),
(115,'VAISH','ACCOUNTS'),
(116,'SHIV','FINANCE'),
(117,'VISHAL','TELUGU'),
(118,'SHURTHI','BIOLOGY'),
(119,'AKSHI','OPERATIONS'),
(120,'SAKTHI','REATILOPERATIONS')
ALTER TABLE PROFESSOR_TABLE
ADD COLLEGE_ID INT 
SELECT * FROM PROFESSOR_TABLE

INSERT INTO STUDENT_TABLE(STUDENT_ID,STUDENT_NAME,STUDENT_STREAM)
VALUES
(1,'RAKESH','COMPUTER SCIENCE'),
(2,'MUKESH','FINANCE'),
(3,'MAHESH','ACCOUNTS'),
(4,'RAMESH','STATISTICS'),
(5,'SUKESH','PHYSICS'),
(6,'BOB SMITH','MANAGEMENT'),
(7,'HENDRY','LAW'),
(8,'JACK','MEDICAL'),
(9,'GRACE','BUSSINESS'),
(10,'ALICE','MECHANICAL')
--TASK 2 
SELECT COLLEGE_ID, COLLEGE_NAME FROM COLLEGE_TABLE
SELECT TOP 5 * FROM STUDENT_TABLE

SELECT * FROM PROFESSOR_TABLE
WHERE PROFESSOR_ID=115

SELECT UPPER(PROFESSOR_NAME) AS UPCASE FROM PROFESSOR_TABLE

SELECT * FROM STUDENT_TABLE
WHERE STUDENT_NAME LIKE 'A%'

SELECT * FROM COLLEGE_TABLE
WHERE COLLEGE_NAME LIKE '%A'

SELECT * FROM PROFESSOR_TABLE
ALTER TABLE PROFESSOR_TABLE
ADD SALARY FLOAT;

SELECT * FROM STUDENT_TABLE
ALTER TABLE STUDENT_TABLE
ADD CONTACT VARCHAR(100);

SELECT SUM(SALARY) AS TOTAL_SAL
FROM PROFESSOR_TABLE


SELECT * FROM STUDENT_TABLE

SELECT TOP 5 *FROM STUDENT_TABLE
UNION ALL
SELECT TOP 5 * FROM PROFESSOR_TABLE


